system:
  device: "cpu"
data:
  relative_data_path: "data/"
  data_test_split_fraction: 0.1
  history_length: 9
  batch_size: 4096
  scan_length: 897
train:
  epochs: 50
  filters: 1
  exp_decay_factor: 1
  train_data_corruption_fraction: 0.1
  test_data_corruption_fraction: 0.1
  model_fn: LabelPoseNet
  loss_fn: torch.nn.MSELoss
  optimizer_fn: torch.optim.Adam
load:
  model_path: ""

